# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de1ed1bea764a1d0e03514004e3fe76a13e8bf932d365367e7b5b548b53308a66aa039d2452ee6547ae2faac102df9c69d1c2901eea0996d9a415594f01c10ef

test:
  secret_key_base: a6780637dabc9e2bb8eb23e179fea544f470f3fbab00a34285b55b3c6ccacd6eb3f7f1b4b740ac53561f54530b43fb1401bab57b0d5ad15a3086aa4fe0b34ab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
